apiVersion: v1
kind: Deployment
metadata:
  name: sample-angular-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      # - name: nginx-container
      #   image: nginx:latest
      #   ports:
      #   - containerPort: 80
      - name: sample-angular-app
        #image: dvalley56/sample-angular-app
        image: 234563/antsy:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80