apiVersion: v1
kind: Service
metadata:
  name: lb-frontend-service
  labels:
    app: lb-frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 8090
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  # minReadySeconds: 30
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: 234563/antsy:v3
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
          - containerPort: 80